spring:
  application:
    name: "Agile Metrics Backend"
  data:
    mongodb:
      uri: mongodb://mongo-user:secret@localhost:27017/agile-metrics?authSource=admin

server:
  port: 8080

agile-metrics:
  azure-project:
    base-url: https://dev.azure.com/

---
  spring:
    profiles: azure
    data:
      mongodb:
        uri: mongodb://mongo-user:secret@mongo:27017/agile-metrics?authSource=admin

---
spring:
  profiles: local

populate-database: true

#logging:
#  level:
#    org:
#      springframework: DEBUG
#        data:
#          mongodb: DEBUG
