spring:
  application:
    name: "Agile Metrics Backend"
  data:
    mongodb:
      uri: mongodb://mongo-user:secret@localhost:27017/agile-metrics?authSource=admin

server:
  port: 8080

#logging:
#  level:
#    org:
#      springframework: DEBUG
#        data:
#          mongodb: DEBUG
