apiVersion: v1
kind: Service
metadata:
    name: agilemetricsbackend
    labels:
        app: agilemetricsbackend
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: agilemetricsbackend